version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python producer.py

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python consumer.py
